// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvOxqHlvmd6t4_5GVvpEWwC03hPNaCzg',
    appId: '1:519658991573:web:eb2fc64f4207252f0e975c',
    messagingSenderId: '519658991573',
    projectId: 'kigali-city-directory-ca5db',
    authDomain: 'kigali-city-directory-ca5db.firebaseapp.com',
    storageBucket: 'kigali-city-directory-ca5db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1d-LU86g4HrfJkBlBcXBsWDGSvei_NnU',
    appId: '1:519658991573:android:e9d91070de3754810e975c',
    messagingSenderId: '519658991573',
    projectId: 'kigali-city-directory-ca5db',
    storageBucket: 'kigali-city-directory-ca5db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHaTr-IclhWZhw-o8vkl7n_MN8-2_k2YM',
    appId: '1:519658991573:ios:6626fdd68030ed820e975c',
    messagingSenderId: '519658991573',
    projectId: 'kigali-city-directory-ca5db',
    storageBucket: 'kigali-city-directory-ca5db.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHaTr-IclhWZhw-o8vkl7n_MN8-2_k2YM',
    appId: '1:519658991573:ios:6626fdd68030ed820e975c',
    messagingSenderId: '519658991573',
    projectId: 'kigali-city-directory-ca5db',
    storageBucket: 'kigali-city-directory-ca5db.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrvOxqHlvmd6t4_5GVvpEWwC03hPNaCzg',
    appId: '1:519658991573:web:4b6236fcb1b471b80e975c',
    messagingSenderId: '519658991573',
    projectId: 'kigali-city-directory-ca5db',
    authDomain: 'kigali-city-directory-ca5db.firebaseapp.com',
    storageBucket: 'kigali-city-directory-ca5db.firebasestorage.app',
  );

}